# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QtB8ed9XsvhyxFw_JpSj8gckDxnYK7k
"""

import math

print("Calculadora: essa calculadora tem as seguintes funções:\n")

print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
print("5 - Potência")
print("6 - Raiz quadrada")
print("7 - Resto")
print("8 - Porcentagem")
print("9 - Valor absoluto")
print("10 - Fatorial")
print("11 - Maior número")
print("12 - Menor número")
print("13 - Média")
print("14 - Dobro")
print("15 - Triplo")
print("16 - Quadrado")
print("17 - Cubo")
print("18 - Inverso")
print("19 - Par ou ímpar")
print("20 - Vê qual o maior numero")

opcao = int(input("\nEscolha uma opção: "))


if opcao == 1:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    print(a + b)

elif opcao == 2:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    print(a - b)

elif opcao == 3:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    print(a * b)

elif opcao == 4:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    if b != 0:
        print(a / b)
    else:
        print("Erro: divisão por zero")

elif opcao == 5:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    print(a ** b)

elif opcao == 6:
    x = float(input("Número: "))
    if x >= 0:
        print(math.sqrt(x))
    else:
        print("Erro: número negativo")

elif opcao == 7:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    print(a % b)

elif opcao == 8:
    a = float(input("Valor: "))
    b = float(input("Porcentagem: "))
    print((a * b) / 100)

elif opcao == 9:
    x = float(input("Número: "))
    print(abs(x))

elif opcao == 10:
    x = int(input("Número: "))
    if x >= 0:
        print(math.factorial(x))
    else:
        print("Erro: número negativo")

elif opcao == 11:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    if a > b:
        print(a)
    else:
        print(b)

elif opcao == 12:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    if a < b:
        print(a)
    else:
        print(b)

elif opcao == 13:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    print((a + b) / 2)

elif opcao == 14:
    x = float(input("Número: "))
    print(x * 2)

elif opcao == 15:
    x = float(input("Número: "))
    print(x * 3)

elif opcao == 16:
    x = float(input("Número: "))
    print(x ** 2)

elif opcao == 17:
    x = float(input("Número: "))
    print(x ** 3)

elif opcao == 18:
    x = float(input("Número: "))
    if x != 0:
        print(1 / x)
    else:
        print("Erro: divisão por zero")

elif opcao == 19:
    x = int(input("Número: "))
    if x % 2 == 0:
        print("Par")
    else:
        print("Ímpar")

elif opcao == 20:
    a = float(input("Número 1: "))
    b = float(input("Número 2: "))
    if a > b:
        print("Primeiro maior")
    elif b > a:
        print("Segundo maior")
    else:
        print("Iguais")

else:
    print("Opção inválida")